### ISSUE TITLE
Pathline stuck

### ISSUE THREAD

**Issue by pettrs** [Maurits825/herbi-afk#4]
when approaching this trail object (unsure of what exact combination of path), the line does not update to the next trail object 
![image](https://user-images.githubusercontent.com/75093127/143203470-0ddfbbd7-2448-4365-ad65-9937d8c4bc5a.png)

**Comment by Maurits825** [comment]
I havent seen this bug yet. If you come across it again, could you try to log the path or the start point, might make it easier to reproduce this problem.

**Comment by Maurits825** [comment]
![herbi-afk-path-bug](https://user-images.githubusercontent.com/63048736/143788538-c588a006-6b6b-4dc3-a244-78f49903d61d.png)

**Comment by Maurits825** [comment]
This spot doesnt get added to the `currentPath` because of this [line in the runelite herbi plugin.](https://github.com/runelite/runelite/blob/45b85bff6a687f5c5eab94d9e97f90a30896ae8f/runelite-client/src/main/java/net/runelite/client/plugins/herbiboars/HerbiboarPlugin.java#L211) Searching the spot gives you the 'leading in circles' message and you have to start over again.

**Comment by Maurits825** [comment]
the plugin now checks for the 'leading in circles' message and will update the pathline to start again
